name: Run CI after Snyk PRs

on:
  pull_request:
    branches: snyk*

jobs:
  build-and-test:
    name: Rebuild with Snyk PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: mvn package --file pom.xml
